### ISSUE TITLE
Mimetype Bug

### ISSUE THREAD

**Issue by denodster** [filestack/filestack-js#245]
So I've got a file: Name.msg

This file is a microsoft outlook email message file (similar to a .eml file but non-standard...)
This file was emailed to me and I'm on a mac.

I use the file command in bash as follows:
```
$ file --mime-type -b Name.msg 
```
And the file command gives me the correct mimetype for this file.
```
application/vnd.ms-outlook
```
However, when I upload to filestack, the mimetype is reported as 'undefined' in the javascript object returned by the callback.

And after completing the upload, if I use the metadata endpoint as follows:

`https://cdn.filestackcontent.com/{{handle}}/metadata`

I get this back for mimetype:

mimetype | "application/x-msi"

which is wrong.

I know the file command can do it, so I must assume that filestack has a bug in it.

**Comment by pcholuj** [comment]
Hi there is an open bug in the library that we are using for detecting mimetype
https://github.com/sindresorhus/file-type/issues/162
I will try to make some workaround for this until it will be fixed.

**Comment by denodster** [comment]
That explains the back end issue, but shouldn't the frontend be coming back with 'Applicaiton/x-msi' rather than 'undefined'?

**Comment by denodster** [comment]
I just got an email from filestack that the back end issue was fixed. I'll follow up and see if this is still a front end issue.

**Comment by denodster** [comment]
no luck I'm still getting back an undefined mimetype.

I'm using: "//static.filestackapi.com/filestack-js/3.x.x/filestack.min.js"

Heres the fp file I get back from the inital upload:
![redacted_fpfile](https://user-images.githubusercontent.com/1984743/62053849-7086fd00-b1e6-11e9-91aa-e0a022560bfa.png)

**Comment by andrewlock** [comment]
Looks like this bug is still around? I see `mimetype`: `undefined` even though the `complete` network call returns the mimetype successfully?

**Comment by WayneUong** [comment]
when I upload a `.csv` file on the server side, the mimetype is detected to be `text/plain` so when I try to download the file, its extension becomes `.txt`, which is a serious problem.

**Comment by pcholuj** [comment]
Please check the newest release. It should work.
