### ISSUE TITLE
Google Drive authentication issue on Safari

### ISSUE THREAD

**Issue by SasSam** [filestack/filestack-js#32]
Hi,

When I set a policy and signature for Filestack v3 picker and I try to sign in with Google Drive on Safari, it throws an error message after entered the email and password in Google auth. page. 

> "Api key not found. Be sure that you are setting it with filepicker.setKey(). If you need an api key or forgot yours, head on over to https://developers.filepicker.io"

Please see uploaded screenshot: http://ibb.co/bD3nxv 

It's an error for v2, but I use v3.

Please check my setup (note: it doesn't work as the API key, Signature and Policy are invalid).

```
var options = {
  apiKey: 'XXXX',
  policy: 'XXXX',
  signature: 'XXXX',
  enabledProviders: ['local_file_system', 'googledrive'],
  acceptedFileTypes: ['.pdf', '.txt', '.rtf'],
  fileSizeLimit = 1024 * 1024 * 2.5
};

var client = filestack.init(options.apiKey, { 'policy': options.policy, 'signature': options.signature });

client.pick({
  maxFiles: 1,
  fromSources: options.enabledProviders,
  accept: options.acceptedFileTypes,
  maxSize: options.fileSizeLimit,
  uploadInBackground: false,
  hideWhenUploading: false,
  onFileSelected: function (file) {
    console.log(result);
  }  
}).then(function (result) {
  console.log(result);
});

```
The code is working anyway. I tried with Chrome and other browsers. It's happening only on Safari.

Any idea? Thanks!

**Comment by velveteer** [comment]
Thanks for reporting, this is unfortunately a known issue. The API still uses cookies to communicate session information (it's the same API used by v2), so tracking OAuth sessions will not work when third-party cookies are disabled (like by default in Safari). If you enable third-party cookies it should work, but we know this is not ideal at all. 

I am working with our backend engineers to ensure that we can retrieve this information without cookies.

**Comment by SasSam** [comment]
@velveteer Thanks for the answer! Any ETA for the fix?

**Comment by realyze** [comment]
@velveteer I'm actually getting this error in Google Chrome 60 on OS X too. I'm trying to upload a file from Google Drive.

"Api key not found. Be sure that you are setting it with filepicker.setKey(). If you need an api key or forgot yours, head on over to https://developers.filepicker.io"

URL is `https://dialog.filestackapi.com/dialog/open/?auth=true#/GoogleDrive/`

**Comment by velveteer** [comment]
@realyze Can you confirm if third-party cookies are enabled in your browser?

I am still working with the backend to resolve this particular issue. It seems at least in Safari on default settings the problem is resolved after trying the redirect flow once more, since the user has already visited the Filestack API domain after the initial error. If anything we need to fix this outdated error page from triggering, and then we can move forward on finding a better solution overall.

I will update this issue with more information once I have it.

**Comment by velveteer** [comment]
Update here.

I haven't been able to achieve any architecture changes on the backend yet (e.g. ditching cookies), but I have implemented a client-side solution. Granted this fix still assumes end-users have cookies enabled, but it should at least resolve the problem with some browsers blocking the Filestack cookie as an untrusted third-party (as seen in the default policy in Safari).

I don't have an exact ETA on release, but I am willing to estimate it could be within the next week or two. I want this issue solved so badly, but we are going to take our time and do some QA before pushing it out.

Thanks to anyone reading this for their patience.

**Comment by petrkrejcik** [comment]
@velveteer I can confirm that the issue still persists for Flickr.
Error message: `Api key not found. Be sure that you are setting it with filepicker.setKey(). If you need an api key or forgot yours, head on over to https://developers.filepicker.io`

Filestack version: 1.8.0
Chrome: 72; MacOS
Block third-party cookies: OFF
Source: Flickr (Google Drive works ok)
